ARG PYTHON_VERSION=3.11.6

FROM jupyter/pyspark-notebook:python-${PYTHON_VERSION}

ARG MLFLOW_VERSION=3.1.1
ARG EXTRA_PIP_PACKAGES=""

RUN pip install --no-cache-dir mlflow[extras]==${MLFLOW_VERSION} ${EXTRA_PIP_PACKAGES}
